name: Example workflow using Snyk with continue on error
on: push

env:
  secrets.SNYK_TOKEN: fb668e2f-e251-48ef-9693-bc87ae55b7b9
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
